"""Generate SVG paths from the pinned Taiwan Atlas topology; Python stdlib only."""
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
atlas = json.loads((ROOT / 'data/taiwan-atlas-towns-10t.json').read_text())
scale, translate = atlas['transform']['scale'], atlas['transform']['translate']
arcs = []
for encoded in atlas['arcs']:
    x = y = 0
    points = []
    for dx, dy in encoded:
        x, y = x + dx, y + dy
        points.append((x * scale[0] + translate[0], y * scale[1] + translate[1]))
    arcs.append(points)


def ring(ids):
    points = []
    for i in ids:
        segment = arcs[i] if i >= 0 else list(reversed(arcs[~i]))
        points.extend(segment if not points else segment[1:])
    assert points[0] == points[-1], 'Topology ring must close'
    return points


def polygons(obj):
    if obj['type'] == 'GeometryCollection':
        return [p for g in obj['geometries'] for p in polygons(g)]
    groups = obj['arcs'] if obj['type'] == 'MultiPolygon' else [obj['arcs']]
    return [[ring(r) for r in p] for p in groups]


def area(p):
    r = p[0]
    return abs(sum(a[0]*b[1]-b[0]*a[1] for a, b in zip(r, r[1:]))) / 2


def mercator(point):
    lon, lat = map(math.radians, point)
    return lon, -math.log(math.tan(math.pi/4 + lat/2))


def projection(polys, padding):
    pts = [mercator(p) for poly in polys for r in poly for p in r]
    x0, y0 = map(min, zip(*pts))
    x1, y1 = map(max, zip(*pts))
    k = min((360-2*padding)/(x1-x0), (560-2*padding)/(y1-y0))
    def project(point):
        x, y = mercator(point)
        return [round(180+k*(x-(x0+x1)/2), 2), round(280+k*(y-(y0+y1)/2), 2)]
    return project


def path(polys, project):
    return ''.join('M' + 'L'.join(','.join(map(str, project(p))) for p in r) + 'Z'
                   for poly in polys for r in poly)


mainland = [max(polygons(atlas['objects']['nation']), key=area)]
county_obj = next(g for g in atlas['objects']['counties']['geometries']
                  if g['properties']['COUNTYCODE'] == '10015')
county = polygons(county_obj)
towns = [g for g in atlas['objects']['towns']['geometries']
         if g['properties']['COUNTYCODE'] == '10015']
assert len(towns) == 13
assert 2 < area(mainland[0]) < 4, 'Expected Taiwan main island'
overview, detail = projection(mainland, 42), projection(county, 42)
# Draw shared township arcs exactly once; omit the outer county border.
owners = {}
for town in towns:
    for poly in (town['arcs'] if town['type'] == 'MultiPolygon' else [town['arcs']]):
        for r in poly:
            for i in r:
                key = i if i >= 0 else ~i
                owners[key] = owners.get(key, 0) + 1
boundaries = ''.join('M'+'L'.join(','.join(map(str, detail(p))) for p in arcs[i])
                     for i, count in owners.items() if count == 2)
places = json.loads((ROOT / 'data/places.json').read_text())
for p in places:
    p['point'] = detail([p['lon'], p['lat']])
result = dict(taiwan=path(mainland, overview), highlight=path(county, overview),
              county=path(county, detail), boundaries=boundaries,
              towns=[t['properties']['TOWNNAME'] for t in towns], places=places)
(ROOT / 'map-data.js').write_text('// Generated by scripts/build_map.py. Do not hand-edit outlines.\n'
                                + 'const MAP_DATA = ' + json.dumps(result, ensure_ascii=False, separators=(',', ':')) + ';\n')
print('Generated mainland, Hualien, 13 townships, and places:', [p['point'] for p in places])
