"""Generate SVG paths from the pinned Taiwan Atlas topology; Python stdlib only."""
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
atlas = json.loads((ROOT / 'data/taiwan-atlas-towns-10t.json').read_text())
scale, translate = atlas['transform']['scale'], atlas['transform']['translate']
arcs = []
for encoded in atlas['arcs']:
    x = y = 0
    points = []
    for dx, dy in encoded:
        x, y = x + dx, y + dy
        points.append((x * scale[0] + translate[0], y * scale[1] + translate[1]))
    arcs.append(points)


def ring(ids):
    points = []
    for i in ids:
        segment = arcs[i] if i >= 0 else list(reversed(arcs[~i]))
        points.extend(segment if not points else segment[1:])
    assert points[0] == points[-1], 'Topology ring must close'
    return points


def polygons(obj):
    if obj['type'] == 'GeometryCollection':
        return [p for g in obj['geometries'] for p in polygons(g)]
    groups = obj['arcs'] if obj['type'] == 'MultiPolygon' else [obj['arcs']]
    return [[ring(r) for r in p] for p in groups]


def area(p):
    r = p[0]
    return abs(sum(a[0]*b[1]-b[0]*a[1] for a, b in zip(r, r[1:]))) / 2


def mercator(point):
    lon, lat = map(math.radians, point)
    return lon, -math.log(math.tan(math.pi/4 + lat/2))


def projection(polys, padding):
    pts = [mercator(p) for poly in polys for r in poly for p in r]
    x0, y0 = map(min, zip(*pts))
    x1, y1 = map(max, zip(*pts))
    k = min((360-2*padding)/(x1-x0), (560-2*padding)/(y1-y0))
    def project(point):
        x, y = mercator(point)
        return [round(180+k*(x-(x0+x1)/2), 2), round(280+k*(y-(y0+y1)/2), 2)]
    return project


def path(polys, project):
    return ''.join('M' + 'L'.join(','.join(map(str, project(p))) for p in r) + 'Z'
                   for poly in polys for r in poly)


mainland = [max(polygons(atlas['objects']['nation']), key=area)]
county_obj = next(g for g in atlas['objects']['counties']['geometries']
                  if g['properties']['COUNTYCODE'] == '10015')
county = polygons(county_obj)
towns = [g for g in atlas['objects']['towns']['geometries']
         if g['properties']['COUNTYCODE'] == '10015']
assert len(towns) == 13
assert 2 < area(mainland[0]) < 4, 'Expected Taiwan main island'
overview, detail = projection(mainland, 42), projection(county, 42)
# Draw shared township arcs exactly once; omit the outer county border.
owners = {}
for town in towns:
    for poly in (town['arcs'] if town['type'] == 'MultiPolygon' else [town['arcs']]):
        for r in poly:
            for i in r:
                key = i if i >= 0 else ~i
                owners[key] = owners.get(key, 0) + 1
boundaries = ''.join('M'+'L'.join(','.join(map(str, detail(p))) for p in arcs[i])
                     for i, count in owners.items() if count == 2)
places = json.loads((ROOT / 'data/places.json').read_text())
for p in places:
    p['point'] = detail([p['lon'], p['lat']])
regions = []
for id, name, zh, label in [('city','시가지','花蓮市',[276,155]), ('school','학교','志學村',[130,215]), ('shoufeng','소우펑','壽豐鄉',[262,274]), ('ruisui','루이수이','瑞穗鄉',[104,367])]:
    polys = json.loads((ROOT / 'data/zhixue.geojson').read_text())['geometry']['coordinates'] if id == 'school' else polygons(next(t for t in towns if t['properties']['TOWNNAME'] == zh))
    pts = [detail(p) for poly in polys for r in poly for p in r]
    xs, ys = zip(*pts)
    regions.append(dict(id=id, name=name, zh=zh, label=label, path=path(polys, detail), bounds=[min(xs),min(ys),max(xs),max(ys)]))
result = dict(regions=regions, taiwan=path(mainland, overview), highlight=path(county, overview),
              county=path(county, detail), boundaries=boundaries,
              towns=[t['properties']['TOWNNAME'] for t in towns], places=places)
(ROOT / 'map-data.js').write_text('// Generated by scripts/build_map.py. Do not hand-edit outlines.\n'
                                + 'const MAP_DATA = ' + json.dumps(result, ensure_ascii=False, separators=(',', ':')) + ';\n')
print('Generated mainland, Hualien, 13 townships, and places:', [p['point'] for p in places])

# Neighbor labels use shared administrative arcs, never guessed proximity.
def arc_ids(town):
    groups = town['arcs'] if town['type'] == 'MultiPolygon' else [town['arcs']]
    return {i if i >= 0 else ~i for poly in groups for r in poly for i in r}


def clip_ring(points):
    for axis, edge, sign in [(0, 26, 1), (0, 334, -1), (1, 76, 1), (1, 506, -1)]:
        output = []
        if not points:
            break
        previous = points[-1]
        for current in points:
            a, b = sign*(previous[axis]-edge)>=0, sign*(current[axis]-edge)>=0
            if a != b:
                fraction = (edge-previous[axis])/(current[axis]-previous[axis])
                output.append([previous[j]+fraction*(current[j]-previous[j]) for j in (0,1)])
            if b:
                output.append(current)
            previous = current
        points = output
    return points


def inside(point, points):
    x, y = point
    result = False
    for a, b in zip(points, points[1:]+points[:1]):
        if (a[1]>y) != (b[1]>y) and x < (b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0]:
            result = not result
    return result


neighbor_labels = {}
for region in regions:
    if region['id'] not in ('shoufeng', 'ruisui'):
        continue
    current = next(t for t in towns if t['properties']['TOWNNAME'] == region['zh'])
    neighbors = [t for t in towns if t is not current and arc_ids(t) & arc_ids(current)]
    x0,y0,x1,y1 = region['bounds']
    k = min(264/(x1-x0),408/(y1-y0))
    tx,ty = 180-k*(x0+x1)/2,302-k*(y0+y1)/2
    blocked = []
    for place in places:
        if place['regionId'] != region['id']:
            continue
        px,py = place['point'][0]*k+tx,place['point'][1]*k+ty
        width = max(len(place.get('mapName',place['name']))*12,len(place['zh'])*10)+8
        blocked.append([px-14-width if px>180 else px-10,py-20,px+10 if px>180 else px+14+width,py+22])
    labels = []
    for neighbor in neighbors:
        name = neighbor['properties']['TOWNNAME']
        candidates = []
        for poly in polygons(neighbor):
            points = clip_ring([[detail(p)[0]*k+tx, detail(p)[1]*k+ty] for p in poly[0]])
            if len(points)<3:
                continue
            pairs = list(zip(points, points[1:]+points[:1]))
            cross = [a[0]*b[1]-b[0]*a[1] for a,b in pairs]
            total = sum(cross)
            if abs(total)<1:
                continue
            center = [sum((a[j]+b[j])*c for (a,b),c in zip(pairs,cross))/(3*total) for j in (0,1)]
            half = len(name)*6+3
            def fits(x,y):
                if any(x+half>b[0] and x-half<b[2] and y+10>b[1] and y-10<b[3] for b in blocked):
                    return False
                return all(inside([x+dx,y+dy],points) for dx,dy in [(0,0),(-half,-9),(half,-9),(-half,9),(half,9)])
            options = [center] if fits(*center) else [[x,y] for x in range(48,313,6) for y in range(88,495,6) if fits(x,y)]
            if options:
                best = min(options,key=lambda p:(p[0]-center[0])**2+(p[1]-center[1])**2)
                candidates.append((abs(total),best))
        if candidates:
            _,point = max(candidates)
            labels.append(dict(name=name,point=[round((point[0]-tx)/k,3),round((point[1]-ty)/k,3)]))
    neighbor_labels[region['id']] = labels
    print(region['zh'], 'adjacent:', [t['properties']['TOWNNAME'] for t in neighbors], 'visible:', [l['name'] for l in labels])
(ROOT/'neighbor-labels.js').write_text('// Generated by scripts/build_map.py from shared township boundaries.\nconst NEIGHBOR_LABELS = '+json.dumps(neighbor_labels,ensure_ascii=False,separators=(',',':'))+';\n')
