"""Build browser note data from one-note-per-file Markdown sources; Python stdlib only."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NOTES_DIR = ROOT / "notes"
OUTPUT = ROOT / "notes.js"


def parse_note(path):
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"{path.name}: missing front matter")

    try:
        _, front, body = text.split("---\n", 2)
    except ValueError as exc:
        raise ValueError(f"{path.name}: malformed front matter") from exc

    meta = {}
    for raw in front.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            raise ValueError(f"{path.name}: invalid front matter line: {raw}")
        key, value = line.split(":", 1)
        meta[key.strip()] = value.strip()

    title = meta.get("title", "").strip()
    regions = [item.strip() for item in meta.get("regions", "").split(",") if item.strip()]
    if not title:
        raise ValueError(f"{path.name}: title is required")
    if not regions:
        raise ValueError(f"{path.name}: regions is required")

    note = {
        "id": path.stem,
        "regionIds": regions,
        "title": title,
        "source": path.relative_to(ROOT).as_posix(),
    }
    body = body.strip()
    if body:
        note["body"] = body
    return note


paths = sorted(p for p in NOTES_DIR.glob("*.md") if p.is_file())
notes = [parse_note(path) for path in paths]

ids = [note["id"] for note in notes]
if len(ids) != len(set(ids)):
    raise ValueError("duplicate note id")

OUTPUT.write_text(
    "// Generated by scripts/build_notes.py from notes/*.md. Do not hand-edit.\n"
    + "const REGION_NOTES = "
    + json.dumps(notes, ensure_ascii=False, separators=(",", ":"))
    + ";\n",
    encoding="utf-8",
)
print(f"Generated {len(notes)} notes from {NOTES_DIR.relative_to(ROOT)}/")
